export default  {
  Departments:[
    { id: "dep0", name: "Mathematics" },
    { id: "dep1", name: "Physics" },
    { id: "dep2", name: "Chemistry" },
    { id: "dep3", name: "Biology" },
    { id: "dep4", name: "Computer Science" },
    { id: "dep5", name: "Engineering" },
    { id: "dep6", name: "Medicine" },
    { id: "dep7", name: "Nursing" },
    { id: "dep8", name: "Business Administration" },
    { id: "dep9", name: "Economics" },
    { id: "dep10", name: "Accounting" },
    { id: "dep11", name: "Education" },
    { id: "dep12", name: "Law" },
    { id: "dep13", name: "Psychology" },
    { id: "dep14", name: "Sociology" },
    { id: "dep15", name: "Political Science" },
    { id: "dep16", name: "History" },
    { id: "dep17", name: "Philosophy" },
    { id: "dep18", name: "Literature" },
    { id: "dep19", name: "Linguistics" },
    { id: "dep20", name: "Art and Design" },
    { id: "dep21", name: "Music" },
    { id: "dep22", name: "Theater and Performing Arts" },
    { id: "dep23", name: "Architecture" },
    { id: "dep24", name: "Environmental Science" },
    { id: "dep25", name: "Geology" },
    { id: "dep26", name: "Agriculture" },
    { id: "dep27", name: "Anthropology" },
    { id: "dep28", name: "Foreign Languages" },
    { id: "dep29", name: "Physical Education and Sports" }
  ],
  Course:[
    { id: "cor0", name: "Math" },
    { id: "cor1", name: "Physics" },
    { id: "cor2", name: "Chemistry" },
    { id: "cor3", name: "Biology" },
    { id: "cor4", name: "Computer Science" },
    { id: "cor5", name: "English" },
    { id: "cor6", name: "History" },
    { id: "cor7", name: "Political Science" },
    { id: "cor8", name: "Economics" },
    { id: "cor9", name: "Psychology" },
    { id: "cor10", name: "Sociology" },
    { id: "cor11", name: "Philosophy" },
    { id: "cor12", name: "Art" },
    { id: "cor13", name: "Music" },
    { id: "cor14", name: "Theatre" },
    { id: "cor15", name: "Business Administration" },
    { id: "cor16", name: "Accounting" },
    { id: "cor17", name: "Finance" },
    { id: "cor18", name: "Marketing" },
    { id: "cor19", name: "Management" },
    { id: "cor20", name: "Engineering" },
    { id: "cor21", name: "Mechanical Engineering" },
    { id: "cor22", name: "Electrical Engineering" },
    { id: "cor23", name: "Civil Engineering" },
    { id: "cor24", name: "Chemical Engineering" },
    { id: "cor25", name: "Aerospace Engineering" },
    { id: "cor26", name: "Environmental Science" },
    { id: "cor27", name: "Health Sciences" },
    { id: "cor28", name: "Nursing" },
    { id: "cor29", name: "Pharmacy" },
    { id: "cor30", name: "Law" },
    { id: "cor31", name: "Education" },
    { id: "cor32", name: "Architecture" },
    { id: "cor33", name: "Journalism" },
    { id: "cor34", name: "Media Studies" },
    { id: "cor35", name: "Anthropology" },
    { id: "cor36", name: "Geology" },
    { id: "cor37", name: "Astronomy" },
    { id: "cor38", name: "Statistics" },
    { id: "cor39", name: "Foreign Languages" },
    { id: "cor40", name: "Ethnic Studies" },
    { id: "cor41", name: "Religious Studies" },
    { id: "cor42", name: "International Relations" },
    { id: "cor43", name: "Public Health" },
    { id: "cor44", name: "Urban Studies" },
    { id: "cor45", name: "Criminology" },
    { id: "cor46", name: "Social Work" },
    { id: "cor47", name: "Kinesiology" },
    { id: "cor48", name: "Cultural Studies" }
  ]
  
}
