export default {
  Departments:[
    { id: "dep0", name: "Mathematics" },
    { id: "dep1", name: "Physics" },
    { id: "dep2", name: "Chemistry" },
    { id: "dep3", name: "Biology" },
    { id: "dep4", name: "Computer Science" },
    { id: "dep5", name: "Engineering" },
    { id: "dep6", name: "Medicine" },
    { id: "dep7", name: "Nursing" },
    { id: "dep8", name: "Business Administration" },
    { id: "dep9", name: "Economics" },
    { id: "dep10", name: "Accounting" },
    { id: "dep11", name: "Education" },
    { id: "dep12", name: "Law" },
    { id: "dep13", name: "Psychology" },
    { id: "dep14", name: "Sociology" },
    { id: "dep15", name: "Political Science" },
    { id: "dep16", name: "History" },
    { id: "dep17", name: "Philosophy" },
    { id: "dep18", name: "Literature" },
    { id: "dep19", name: "Linguistics" },
    { id: "dep20", name: "Art and Design" },
    { id: "dep21", name: "Music" },
    { id: "dep22", name: "Theater and Performing Arts" },
    { id: "dep23", name: "Architecture" },
    { id: "dep24", name: "Environmental Science" },
    { id: "dep25", name: "Geology" },
    { id: "dep26", name: "Agriculture" },
    { id: "dep27", name: "Anthropology" },
    { id: "dep28", name: "Foreign Languages" },
    { id: "dep29", name: "Physical Education and Sports" }
  ]
}
