// "use client"

import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/HomeLayouts/Header'
import Footer from '@/components/HomeLayouts/Footer'
import { mergeText } from './add'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Scolarite',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <main class="grid grid-rows-[auto_1fr] page-main">
      <Header />
        <main className={mergeText("page-content",inter.className)}>
          {children}
          <Footer />
          </main>
      
    </main>
    </html>
  )
}
