import { Inter ,Montserrat_Alternates,Roboto} from 'next/font/google'
import './globals.css'
import Header from '@/components/HomeLayouts/Header'
import Footer from '@/components/HomeLayouts/Footer'
import { mergeText } from './add'

const inter = Roboto({
  weight: ['300', '400', '500', '700',"900"],
  subsets: ['latin'],
  display:'swap',
  fallback: ['Arial', 'sans-serif'],
});

export const metadata = {
  title: 'Scolarite',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <main className="grid grid-rows-[auto_1fr] page-main">
        <Header />
          <main className={mergeText("page-content",inter.className)}>
            {children}
            <Footer />
            </main>
      
      </main>
    </body>
    </html>
  )
}
